name: caravaggio_ui
description: "A comprehensive UI package designed to streamline your Flutter app development process."
version: 1.0.5
homepage: "https://caravaggioui.com"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  caravaggio_calendar_picker: ^1.0.0
  device_preview: ^1.3.1
  flutter:
    sdk: flutter
  intl: ^0.20.2
  percent_indicator: ^4.2.3
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
